name: external_deploy
on: [repository_dispatch]
jobs:
    ping-pong:
        runs-on: ubuntu-latest
        steps:
            - name: Event Information
              run: |
                  echo "Event '${{ github.event.action }}', tag = '${{ github.event.client_payload.tag }}'"
